In [4]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [13]:
import numpy as np

a = np.asarray([1,5,6,4,2])
c = [52,15,5,6,1]
b = np.asarray([12,11,5,1,4])
print(f"a : {a}\nc : {c}")
c.sort(reverse=False)
print(f"c after sort :{c}")
print(f"b : {b}")
b = np.argsort(b)
print(f"b arguement sort : {b}")


a : [1 5 6 4 2]
c : [52, 15, 5, 6, 1]
c after sort :[1, 5, 6, 15, 52]
b : [12 11  5  1  4]
b arguement sort : [3 4 2 1 0]


In [5]:
import numpy as np

# create two matrics
metrix_a = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

metrix_b = np.array([[9,8,7],
                    [6,5,4],
                    [3,2,1]])

# Metrix multiplication
result_multiplication = np.matmul(metrix_a, metrix_b)

# Metrix dot product
result_dot_product = np.dot(metrix_a,metrix_b)

# Display

print(f"Metrix a : {metrix_a}")
print(f"Metrix b : {metrix_b}")

print(f"Metrix multiplication : {result_multiplication}")
print(f"Metrix dot product : {result_dot_product}")

Metrix a : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Metrix b : [[9 8 7]
 [6 5 4]
 [3 2 1]]
Metrix multiplication : [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Metrix dot product : [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [6]:
import numpy as np

a = [3,5,85,41,23,6,1]
print(f"a : {a}")
a.sort(reverse=False)
# return a as sort list ascending
print(f"a after sort {a}")

a = [6,1,5,7,9,10]
print(f"new a : {a}")
indx = np.argsort(a)
#Return index of sorting array
print(f"index : {indx}")

#convert list a to np array
print(np.array(a)[indx])


a : [3, 5, 85, 41, 23, 6, 1]
a after sort [1, 3, 5, 6, 23, 41, 85]
new a : [6, 1, 5, 7, 9, 10]
index : [1 2 0 3 4 5]
[ 1  5  6  7  9 10]


In [7]:
import numpy as np

class Person :
    def __init__(self,name,age):
        self.name = name
        self.age =age
    def set_name(self,name):
        self.name = name
    def set_age(self, age):
        self.age = age
    def display_info(self):
        print(f"Name : {self.name} age {self.age}")

#Example
person1 = Person("Pawat",21)

print("Initial Information")
person1.display_info()

Initial Information
Name : Pawat age 21


In [15]:
def facrorial(n):
    if(n == 1) :
        return 1
    else :
        return n*facrorial(n-1)

print(facrorial(5))

120


In [34]:
def fibonacci(n):
    if n == 1 :
        return 0
    elif n == 2 :
        return 1
    else:
        return facrorial(n-1)+facrorial(n-2)

print(fibonacci(4))

8
